#include:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
# https://gitlab.com/gitlab-org/terraform-images
# https://gitlab.com/gitlab-org/terraform-images/-/blob/master/src/bin/gitlab-terraform.sh
#  - template: Terraform.gitlab-ci.yml

stages:
  - plan
  - deploy
  - cleanup


# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
# Terraform/Base.latest
#
# The purpose of this template is to provide flexibility to the user so
# they are able to only include the jobs that they find interesting.
#
# Therefore, this template is not supposed to run any jobs. The idea is to only
# create hidden jobs. See: https://docs.gitlab.com/ee/ci/yaml/#hide-jobs
#
# There is a more opinionated template which we suggest the users to abide,
# which is the lib/gitlab/ci/templates/Terraform.latest.gitlab-ci.yml

image:
  # https://gitlab.com/gitlab-org/terraform-images/container_registry/2018822
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/1.0:v0.31.0
#  name: registry.gitlab.com/gitlab-org/terraform-images/releases/1.0:latest

#============================#
# .plan                      #
#============================#
#.plan:
#  stage: plan
#  variables:
#    TF_ROOT: ./
#    TF_STATE_NAME: default
#  cache:
#    key: "${TF_ROOT}"
#    paths:
#      - ${TF_ROOT}/.terraform/
#      - ${TF_ROOT}/.terraform.lock.hcl
##  before_script:
##    - cd ${TF_ROOT}
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
##    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
##    - cat $DEV_TERRAFORM_VAR_FILE_BASE64 | base64 -d > var_file
#  script:
#    - gitlab-terraform --version
#    - gitlab-terraform init
#    - gitlab-terraform validate
#
#    # -var-file=filename  Load variable values from the given file, in addition
#    #                      to the default files terraform.tfvars and *.auto.tfvars.
#    #                      Use this option more than once to include more than one
#    #                      variables file.
#    # -input=true         Ask for input for variables if not directly set.
#    # -out=path           Write a plan file to the given path. This can be used as
#    #                      input to the "apply" command.
#
#    # plan_cache="plan.cache"
#    # terraform "${@}" -input=false -out="${plan_cache}
#    - gitlab-terraform plan -var-file=var_file
#
#    # https://gitlab.com/gitlab-org/terraform-images/-/blob/master/src/bin/gitlab-terraform.sh
#    # terraform show -json "${plan_cache}" | jq -r "${JQ_PLAN}" > "${plan_json}"
#    # terraform show: Show the current state or a saved plan
#    # https://stedolan.github.io/jq/
#    # jq- jq is like sed for JSON data - you can use it to slice and filter and map and transform structured data with the same ease that sed, awk, grep and friends let you play with text.
#    - gitlab-terraform plan-json -var-file=var_file
#  resource_group: ${TF_STATE_NAME}
#  artifacts:
#    paths:
#      # The [gitlab-terraform plan] creates this file.
#      - ${TF_ROOT}/plan.cache
#    reports:
#      # The [gitlab-terraform plan-json] creates this file.
#      terraform: ${TF_ROOT}/plan.json
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      when: manual


.plan:
  stage: plan
  variables:
    TF_ROOT: ./
    TF_STATE_NAME: default
  cache:
    key: "${TF_ROOT}"
    paths:
      - ${TF_ROOT}/.terraform/
      - ${TF_ROOT}/.terraform.lock.hcl
    #  before_script:
    #    - cd ${TF_ROOT}
    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
  #    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
  #    - cat $DEV_TERRAFORM_VAR_FILE_BASE64 | base64 -d > var_file
  resource_group: ${TF_STATE_NAME}
  artifacts:
    paths:
      # The [gitlab-terraform plan] creates this file.
      - ${TF_ROOT}/plan.cache
    reports:
      # The [gitlab-terraform plan-json] creates this file.
      terraform: ${TF_ROOT}/plan.json
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual


.plan.with.var.file:
  extends: .plan
  script:
    - gitlab-terraform --version
    - gitlab-terraform init
    - gitlab-terraform validate

    # -var-file=filename  Load variable values from the given file, in addition
    #                      to the default files terraform.tfvars and *.auto.tfvars.
    #                      Use this option more than once to include more than one
    #                      variables file.
    # -input=true         Ask for input for variables if not directly set.
    # -out=path           Write a plan file to the given path. This can be used as
    #                      input to the "apply" command.

    # plan_cache="plan.cache"
    # terraform "${@}" -input=false -out="${plan_cache}
    - gitlab-terraform plan -var-file=var_file

    # https://gitlab.com/gitlab-org/terraform-images/-/blob/master/src/bin/gitlab-terraform.sh
    # terraform show -json "${plan_cache}" | jq -r "${JQ_PLAN}" > "${plan_json}"
    # terraform show: Show the current state or a saved plan
    # https://stedolan.github.io/jq/
    # jq- jq is like sed for JSON data - you can use it to slice and filter and map and transform structured data with the same ease that sed, awk, grep and friends let you play with text.
    - gitlab-terraform plan-json -var-file=var_file

.plan.without.var.file:
  extends: .plan
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform --version
    - gitlab-terraform init
    - gitlab-terraform validate

    # -var-file=filename  Load variable values from the given file, in addition
    #                      to the default files terraform.tfvars and *.auto.tfvars.
    #                      Use this option more than once to include more than one
    #                      variables file.
    # -input=true         Ask for input for variables if not directly set.
    # -out=path           Write a plan file to the given path. This can be used as
    #                      input to the "apply" command.

    # plan_cache="plan.cache"
    # terraform "${@}" -input=false -out="${plan_cache}
    - gitlab-terraform plan

    # https://gitlab.com/gitlab-org/terraform-images/-/blob/master/src/bin/gitlab-terraform.sh
    # terraform show -json "${plan_cache}" | jq -r "${JQ_PLAN}" > "${plan_json}"
    # terraform show: Show the current state or a saved plan
    # https://stedolan.github.io/jq/
    # jq- jq is like sed for JSON data - you can use it to slice and filter and map and transform structured data with the same ease that sed, awk, grep and friends let you play with text.
    - gitlab-terraform plan-json


#============================#
# .apply                     #
#============================#
.apply:
  stage: deploy
  variables:
    TF_ROOT: ./
    TF_STATE_NAME: default
  cache:
    key: "${TF_ROOT}"
    paths:
      - ${TF_ROOT}/.terraform/
      - ${TF_ROOT}/.terraform.lock.hcl
#  before_script:
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
  script:
    - cd ${TF_ROOT}

    # plan_cache="plan.cache"
    # terraform "${@}" -input=false "${plan_cache}"
    - gitlab-terraform apply
  resource_group: ${TF_STATE_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

#============================#
# .destroy                   #
#============================#
#.destroy:
#  stage: cleanup
#  variables:
#    TF_ROOT: ./
#    TF_STATE_NAME: default
#  cache:
#    key: "${TF_ROOT}"
#    paths:
#      - ${TF_ROOT}/.terraform/
#      - ${TF_ROOT}/.terraform.lock.hcl
##  before_script:
##    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
##    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
##    - cd ${TF_ROOT}
##    - cat $TERRAFORM_VAR_FILE_BASE64_DEV | base64 -d > var_file
#  script:
#    # terraform "${@}" -auto-approve
#    - gitlab-terraform destroy -var-file=var_file
#  resource_group: ${TF_STATE_NAME}
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      when: manual

.destroy:
  stage: cleanup
  variables:
    TF_ROOT: ./
    TF_STATE_NAME: default
  cache:
    key: "${TF_ROOT}"
    paths:
      - ${TF_ROOT}/.terraform/
      - ${TF_ROOT}/.terraform.lock.hcl
  #  before_script:
  #    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
  #    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
  #    - cd ${TF_ROOT}
  #    - cat $TERRAFORM_VAR_FILE_BASE64_DEV | base64 -d > var_file

  resource_group: ${TF_STATE_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

.destroy.with.var.file:
  extends: .destroy
  script:
    # terraform "${@}" -auto-approve
    - gitlab-terraform destroy -var-file=var_file

.destroy.without.var.file:
  extends: .destroy
  script:
    - cd ${TF_ROOT}
    # terraform "${@}" -auto-approve
    - gitlab-terraform destroy


#===========================================================#
variables:
  DEV_VPC_DIR: EnvDev/1-VPC
  QA_DIR: EnvQA
  PROD_DIR: EnvProduction

# TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/sre-infra
# ${CI_API_V4_URL} = https://gitlab.com/api/v4
# ${CI_PROJECT_ID} = 27641226

#============================#
# Dev - VPC                  #
#============================#
dev-vpc-plan:
  extends: .plan.without.var.file
  variables:
    TF_ROOT: ${DEV_VPC_DIR}
    TF_STATE_NAME: ${DEV_VPC_DIR}
  before_script:
    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_VPC_SERVICE_ACCOUNT_BASE64 | base64 -d)

dev-vpc-apply:
  extends: .apply
  needs: [dev-vpc-plan]
  variables:
    TF_ROOT: ${DEV_VPC_DIR}
    TF_STATE_NAME: ${DEV_VPC_DIR}
  before_script:
    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_VPC_SERVICE_ACCOUNT_BASE64 | base64 -d)

dev-vpc-destroy:
  extends: .destroy.without.var.file
  needs: [dev-vpc-plan]
  variables:
    TF_ROOT: ${DEV_VPC_DIR}
    TF_STATE_NAME: ${DEV_VPC_DIR}
  before_script:
    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $DEV_VPC_SERVICE_ACCOUNT_BASE64 | base64 -d)









#============================#
# QA                         #
#============================#
#qa-plan:
#  extends: .plan
#  variables:
#    TF_ROOT: ${QA_DIR}
#    TF_STATE_NAME: ${QA_DIR}
#  before_script:
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $PROD_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
#    - cd ${TF_ROOT}
#    - cat $PROD_TERRAFORM_VAR_FILE_BASE64 | base64 -d > var_file
#
#qa-apply:
#  extends: .apply
#  needs: [qa-plan]
#  variables:
#    TF_ROOT: ${QA_DIR}
#    TF_STATE_NAME: ${QA_DIR}
#  before_script:
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $PROD_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
#
#qa-destroy:
#  extends: .destroy
#  needs: [qa-plan]
#  variables:
#    TF_ROOT: ${QA_DIR}
#    TF_STATE_NAME: ${QA_DIR}
#  before_script:
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $PROD_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
#    - cd ${TF_ROOT}
#    - cat $PROD_TERRAFORM_VAR_FILE_BASE64 | base64 -d > var_file


#============================#
# Production                 #
#============================#
#prod-plan:
#  extends: .plan
#  variables:
#    TF_ROOT: ${PROD_DIR}
#    TF_STATE_NAME: ${PROD_DIR}
#  before_script:
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $PROD_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
#    - cd ${TF_ROOT}
#    - cat $PROD_TERRAFORM_VAR_FILE_BASE64 | base64 -d > var_file
#
#prod-apply:
#  extends: .apply
#  needs: [prod-plan]
#  variables:
#    TF_ROOT: ${PROD_DIR}
#    TF_STATE_NAME: ${PROD_DIR}
#  before_script:
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $PROD_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
#
#prod-destroy:
#  extends: .destroy
#  needs: [prod-plan]
#  variables:
#    TF_ROOT: ${PROD_DIR}
#    TF_STATE_NAME: ${PROD_DIR}
#  before_script:
#    # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference
#    - export GOOGLE_CLOUD_KEYFILE_JSON=$(cat $PROD_INFRA_SERVICE_ACCOUNT_BASE64 | base64 -d)
#    - cd ${TF_ROOT}
#    - cat $PROD_TERRAFORM_VAR_FILE_BASE64 | base64 -d > var_file






