apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      endpoint: metrics
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#podmetricsendpoint
  podMetricsEndpoints:
    - port: metrics