{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-argocd
spec:
  stripPrefix:
    prefixes:
      - /argocd
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ig-argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/argocd`)
      middlewares:
        - name: strip-argocd
      services:
        - kind: Service
          name: argocd-server
          port: http
  tls:
    {{- if .Values.ingress.useProdCert }}
    secretName: cert.prod
    {{- else }}
    secretName: cert.staging
    {{- end }}
{{- end }}    