
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mysql
  labels:
    prometheus: example
    role: alert-rules
    # keypoint
    release: prometheus
spec:
  groups:
    - name: mysql
      rules:
        - alert: MysqlDown
          expr: mysql_up == 0
          for: 3m
          labels:
            severity: critical
          annotations:
            summary: "MySQL down"
            description: "MySQL instance is down."
        - alert: MysqlTooManyConnections
          expr: avg by (instance) (rate(mysql_global_status_threads_connected[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: MySQL too many connections
            description: "More than 80% of MySQL connections are in use."
        - alert: MysqlHighThreadsRunning
          expr: avg by (instance) (rate(mysql_global_status_threads_running[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 60
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: MySQL high threads running
            description: "More than 60% of MySQL connections are in running state."
        - alert: MysqlSlaveIoThreadNotRunning
          expr: mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_io_running == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: MySQL Slave IO thread not running
            description: "MySQL Slave IO thread not running on."
        - alert: MysqlSlaveSqlThreadNotRunning
          expr: mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_sql_running == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: MySQL Slave SQL thread not running
            description: "MySQL Slave SQL thread not running."
        - alert: MysqlSlaveReplicationLag
          expr: mysql_slave_status_master_server_id > 0 and ON (instance) (mysql_slave_status_seconds_behind_master - mysql_slave_status_sql_delay) > 30
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: MySQL Slave replication lag
            description: "MySQL replication lag"
        - alert: MysqlSlowQueries
          expr: increase(mysql_global_status_slow_queries[1m]) > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: MySQL slow queries
            description: "MySQL server mysql has some new slow query."
        - alert: MysqlInnodbLogWaits
          expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: MySQL InnoDB log waits
            description: "MySQL innodb log writes stalling"
        - alert: MysqlRestarted
          expr: mysql_global_status_uptime < 60
          for: 0m
          labels:
            severity: info
          annotations:
            summary: MySQL restarted
            description: "MySQL has just been restarted, less than one minute ago"
  
  