apiVersion: v1
kind: Service
metadata:
  name: svc-table
spec:
  selector:
    app: table
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP