apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: slo-official-web
  labels:
    app: official-web
spec:
  groups:
    - name: sloth-slo-sli-recordings-official-web-requests-availability
      rules:
        - record: slo:sli_error:ratio_rate5m
          expr: |
            (sum(rate(http_server_duration_ms_count{job="official-web", http_status_code=~"5..|429"}[5m])))
            /
            (sum(rate(http_server_duration_ms_count{job="official-web"}[5m])))
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 5m
        - record: slo:sli_error:ratio_rate30m
          expr: |
            (sum(rate(http_server_duration_ms_count{job="official-web", http_status_code=~"5..|429"}[30m])))
            /
            (sum(rate(http_server_duration_ms_count{job="official-web"}[30m])))
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 30m
        - record: slo:sli_error:ratio_rate1h
          expr: |
            (sum(rate(http_server_duration_ms_count{job="official-web", http_status_code=~"5..|429"}[1h])))
            /
            (sum(rate(http_server_duration_ms_count{job="official-web"}[1h])))
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 1h
        - record: slo:sli_error:ratio_rate2h
          expr: |
            (sum(rate(http_server_duration_ms_count{job="official-web", http_status_code=~"5..|429"}[2h])))
            /
            (sum(rate(http_server_duration_ms_count{job="official-web"}[2h])))
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 2h
        - record: slo:sli_error:ratio_rate6h
          expr: |
            (sum(rate(http_server_duration_ms_count{job="official-web", http_status_code=~"5..|429"}[6h])))
            /
            (sum(rate(http_server_duration_ms_count{job="official-web"}[6h])))
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 6h
        - record: slo:sli_error:ratio_rate1d
          expr: |
            (sum(rate(http_server_duration_ms_count{job="official-web", http_status_code=~"5..|429"}[1d])))
            /
            (sum(rate(http_server_duration_ms_count{job="official-web"}[1d])))
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 1d
        - record: slo:sli_error:ratio_rate3d
          expr: |
            (sum(rate(http_server_duration_ms_count{job="official-web", http_status_code=~"5..|429"}[3d])))
            /
            (sum(rate(http_server_duration_ms_count{job="official-web"}[3d])))
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 3d
        - record: slo:sli_error:ratio_rate30d
          expr: |
            sum_over_time(slo:sli_error:ratio_rate5m{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"}[30d])
            / ignoring (sloth_window)
            count_over_time(slo:sli_error:ratio_rate5m{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"}[30d])
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_window: 30d
    - name: sloth-slo-meta-recordings-official-web-requests-availability
      rules:
        - record: slo:objective:ratio
          expr: vector(0.9)
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
        - record: slo:error_budget:ratio
          expr: vector(1-0.9)
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
        - record: slo:time_period:days
          expr: vector(30)
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
        - record: slo:current_burn_rate:ratio
          expr: |
            slo:sli_error:ratio_rate5m{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"}
            / on(sloth_id, sloth_slo, sloth_service) group_left
            slo:error_budget:ratio{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"}
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
        - record: slo:period_burn_rate:ratio
          expr: |
            slo:sli_error:ratio_rate30d{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"}
            / on(sloth_id, sloth_slo, sloth_service) group_left
            slo:error_budget:ratio{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"}
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
        - record: slo:period_error_budget_remaining:ratio
          expr: 1 - slo:period_burn_rate:ratio{sloth_id="official-web-requests-availability",
            sloth_service="official-web", sloth_slo="requests-availability"}
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_service: official-web
            sloth_slo: requests-availability
        - record: sloth_slo_info
          expr: vector(1)
          labels:
            project: sk
            sloth_id: official-web-requests-availability
            sloth_mode: cli-gen-prom
            sloth_objective: "90"
            sloth_service: official-web
            sloth_slo: requests-availability
            sloth_spec: prometheus/v1
            sloth_version: fcf9ecf726a80befa3657c84dd31cf08acef81ce
    - name: sloth-slo-alerts-official-web-requests-availability
      rules:
        - alert: OfficialWebHighErrorRate
          expr: |
            (
                max(slo:sli_error:ratio_rate5m{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (14.4 * 0.1)) without (sloth_window)
                and
                max(slo:sli_error:ratio_rate1h{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (14.4 * 0.1)) without (sloth_window)
            )
            or
            (
                max(slo:sli_error:ratio_rate30m{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (6 * 0.1)) without (sloth_window)
                and
                max(slo:sli_error:ratio_rate6h{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (6 * 0.1)) without (sloth_window)
            )
          labels:
            category: availability
            routing_key: sre-team
            severity: page
            sloth_severity: page
          annotations:
            summary: High error rate on 'official-web' requests responses
            title: (page) SLO error budget
              burn rate is too fast.
        - alert: OfficialWebHighErrorRate
          expr: |
            (
                max(slo:sli_error:ratio_rate2h{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (3 * 0.1)) without (sloth_window)
                and
                max(slo:sli_error:ratio_rate1d{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (3 * 0.1)) without (sloth_window)
            )
            or
            (
                max(slo:sli_error:ratio_rate6h{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (1 * 0.1)) without (sloth_window)
                and
                max(slo:sli_error:ratio_rate3d{sloth_id="official-web-requests-availability", sloth_service="official-web", sloth_slo="requests-availability"} > (1 * 0.1)) without (sloth_window)
            )
          labels:
            category: availability
            severity: ticket
            slack_channel: '#sk-sre-info'
            sloth_severity: ticket
          annotations:
            summary: High error rate on 'official-web' requests responses
            title: (ticket) SLO error budget
              burn rate is too fast.
  
  