apiVersion: v1
data:
  tls.crt: {{ required "You should provide public key." .Values.keys.public }}
  tls.key: {{ required "You should provide private key." .Values.keys.private }}
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: kube-system
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls
