## Argo Configs
configs:
  # -- Repositories list to be used by applications
  ## Creates a secret for each key/value specified below to create repositories
  ## Note: the last example in the list would use a repository credential template,
  # configured under "configs.repositoryCredentials".
  repositories:
    sk-table:
      url: https://gitlab.com/GameSnake/SRE/ArgoCDAppTable.git
      name: sk-table
      type: git
      password: my-password
      username: my-username
    sk-file:
      url: https://gitlab.com/GameSnake/SRE/ArgoCDAppFile.git
      name: sk-file
      type: git
      password: my-password
      username: my-username
    sk-user:
      url: https://gitlab.com/GameSnake/SRE/ArgoCDAppUser.git
      name: sk-user
      type: git
      password: my-password
      username: my-username
    sk-backstage:
      url: https://gitlab.com/GameSnake/SRE/ArgoCDAppBackstage.git
      name: sk-backstage
      type: git
      password: my-password
      username: my-username
    sk-battle:
      url: https://gitlab.com/GameSnake/SRE/ArgoCDAppBattle.git
      name: sk-battle
      type: git
      password: my-password
      username: my-username
    
    #  repositories: { }
    # istio-helm-repo:
    #   url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
    #   name: istio.io
    #   type: helm
    # private-helm-repo:
    #   url: https://my-private-chart-repo.internal
    #   name: private-repo
    #   type: helm
    #   password: my-password
    #   username: my-username
  # private-repo:
  #   url: https://github.com/argoproj/private-repo