apiVersion: v1
kind: Namespace
metadata:
  name: table
  labels:
    kubed: sync
---
apiVersion: v1
kind: Namespace
metadata:
  name: user
  labels:
    kubed: sync
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kubed: sync
---
apiVersion: v1
kind: Namespace
metadata:
  name: file
  labels:
    kubed: sync
